#!/bin/sh

#StartUp Applications
$HOME/.config/bspwm/autostart.sh

#fix for moving spotify to specific workspace
bspc config external_rules_command ~/.config/bspwm/scripts/external_rules_command

#BSPWM configuration
bspc config border_width         0
bspc config window_gap           16
bspc config presel_feedback_color	"#5e81ac"

#Single monitor
bspc monitor eDP-1-1 -r
bspc monitor -d 1 2 3 4 5 6

#Rules
bspc rule -a discord desktop=^5 follow=on
bspc rule -a firefox desktop=^1 follow=on
bspc rule -a Zathura state=tiled

